name: Rust

on:
  push:
    branches: [ "main" ]
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            archive: zip

    steps:
    - uses: actions/checkout@v4
    - name: Enable Cargo Cache
      uses: Swatinem/rust-cache@v2.7.3
    - name: Compile and release
      uses: rust-build/rust-build.action@v1.4.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        RUSTTARGET: ${{ matrix.target }}
        ARCHIVE_TYPES: ${{ matrix.archive }}
        EXTRA_FILES: "README.md LICENSE.txt"
        UPLOAD_MODE: none
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Binary
        path: |
          ${{ steps.compile.outputs.BUILT_ARCHIVE }}
          ${{ steps.compile.outputs.BUILT_CHECKSUM }}
